//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbbTest2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Measure", Namespace="http://schemas.datacontract.org/2004/07/AbbTest2.Models")]
    [System.SerializableAttribute()]
    public partial class Measure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<decimal> ActualCurrentAk__BackingFieldField;
        
        private System.Nullable<decimal> ActualPressureBark__BackingFieldField;
        
        private System.Nullable<decimal> ActualRevsRpmk__BackingFieldField;
        
        private System.Nullable<decimal> CurrentAk__BackingFieldField;
        
        private System.Nullable<decimal> Differencek__BackingFieldField;
        
        private System.Nullable<decimal> MaxPressurek__BackingFieldField;
        
        private System.Nullable<decimal> MaxTorquek__BackingFieldField;
        
        private int MeasureIdk__BackingFieldField;
        
        private int MotorIdk__BackingFieldField;
        
        private string MotorNamek__BackingFieldField;
        
        private AbbTest2.ServiceReference1.Motor Motork__BackingFieldField;
        
        private System.TimeSpan Timestampk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActualCurrentA>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> ActualCurrentAk__BackingField {
            get {
                return this.ActualCurrentAk__BackingFieldField;
            }
            set {
                if ((this.ActualCurrentAk__BackingFieldField.Equals(value) != true)) {
                    this.ActualCurrentAk__BackingFieldField = value;
                    this.RaisePropertyChanged("ActualCurrentAk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActualPressureBar>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> ActualPressureBark__BackingField {
            get {
                return this.ActualPressureBark__BackingFieldField;
            }
            set {
                if ((this.ActualPressureBark__BackingFieldField.Equals(value) != true)) {
                    this.ActualPressureBark__BackingFieldField = value;
                    this.RaisePropertyChanged("ActualPressureBark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActualRevsRpm>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> ActualRevsRpmk__BackingField {
            get {
                return this.ActualRevsRpmk__BackingFieldField;
            }
            set {
                if ((this.ActualRevsRpmk__BackingFieldField.Equals(value) != true)) {
                    this.ActualRevsRpmk__BackingFieldField = value;
                    this.RaisePropertyChanged("ActualRevsRpmk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CurrentA>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> CurrentAk__BackingField {
            get {
                return this.CurrentAk__BackingFieldField;
            }
            set {
                if ((this.CurrentAk__BackingFieldField.Equals(value) != true)) {
                    this.CurrentAk__BackingFieldField = value;
                    this.RaisePropertyChanged("CurrentAk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Difference>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> Differencek__BackingField {
            get {
                return this.Differencek__BackingFieldField;
            }
            set {
                if ((this.Differencek__BackingFieldField.Equals(value) != true)) {
                    this.Differencek__BackingFieldField = value;
                    this.RaisePropertyChanged("Differencek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MaxPressure>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> MaxPressurek__BackingField {
            get {
                return this.MaxPressurek__BackingFieldField;
            }
            set {
                if ((this.MaxPressurek__BackingFieldField.Equals(value) != true)) {
                    this.MaxPressurek__BackingFieldField = value;
                    this.RaisePropertyChanged("MaxPressurek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MaxTorque>k__BackingField", IsRequired=true)]
        public System.Nullable<decimal> MaxTorquek__BackingField {
            get {
                return this.MaxTorquek__BackingFieldField;
            }
            set {
                if ((this.MaxTorquek__BackingFieldField.Equals(value) != true)) {
                    this.MaxTorquek__BackingFieldField = value;
                    this.RaisePropertyChanged("MaxTorquek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MeasureId>k__BackingField", IsRequired=true)]
        public int MeasureIdk__BackingField {
            get {
                return this.MeasureIdk__BackingFieldField;
            }
            set {
                if ((this.MeasureIdk__BackingFieldField.Equals(value) != true)) {
                    this.MeasureIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("MeasureIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MotorId>k__BackingField", IsRequired=true)]
        public int MotorIdk__BackingField {
            get {
                return this.MotorIdk__BackingFieldField;
            }
            set {
                if ((this.MotorIdk__BackingFieldField.Equals(value) != true)) {
                    this.MotorIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("MotorIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MotorName>k__BackingField", IsRequired=true)]
        public string MotorNamek__BackingField {
            get {
                return this.MotorNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorNamek__BackingFieldField, value) != true)) {
                    this.MotorNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("MotorNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Motor>k__BackingField", IsRequired=true)]
        public AbbTest2.ServiceReference1.Motor Motork__BackingField {
            get {
                return this.Motork__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Motork__BackingFieldField, value) != true)) {
                    this.Motork__BackingFieldField = value;
                    this.RaisePropertyChanged("Motork__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Timestamp>k__BackingField", IsRequired=true)]
        public System.TimeSpan Timestampk__BackingField {
            get {
                return this.Timestampk__BackingFieldField;
            }
            set {
                if ((this.Timestampk__BackingFieldField.Equals(value) != true)) {
                    this.Timestampk__BackingFieldField = value;
                    this.RaisePropertyChanged("Timestampk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Motor", Namespace="http://schemas.datacontract.org/2004/07/AbbTest2.Models")]
    [System.SerializableAttribute()]
    public partial class Motor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DisplacemntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FuelConsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaxPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxPressureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxTorqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AbbTest2.ServiceReference1.Measure> MeasuresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MotorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<AbbTest2.ServiceReference1.MotorType> MotorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VoltageVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrentA {
            get {
                return this.CurrentAField;
            }
            set {
                if ((this.CurrentAField.Equals(value) != true)) {
                    this.CurrentAField = value;
                    this.RaisePropertyChanged("CurrentA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Displacemnt {
            get {
                return this.DisplacemntField;
            }
            set {
                if ((this.DisplacemntField.Equals(value) != true)) {
                    this.DisplacemntField = value;
                    this.RaisePropertyChanged("Displacemnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FuelCons {
            get {
                return this.FuelConsField;
            }
            set {
                if ((this.FuelConsField.Equals(value) != true)) {
                    this.FuelConsField = value;
                    this.RaisePropertyChanged("FuelCons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxPower {
            get {
                return this.MaxPowerField;
            }
            set {
                if ((this.MaxPowerField.Equals(value) != true)) {
                    this.MaxPowerField = value;
                    this.RaisePropertyChanged("MaxPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MaxPressure {
            get {
                return this.MaxPressureField;
            }
            set {
                if ((this.MaxPressureField.Equals(value) != true)) {
                    this.MaxPressureField = value;
                    this.RaisePropertyChanged("MaxPressure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MaxTorque {
            get {
                return this.MaxTorqueField;
            }
            set {
                if ((this.MaxTorqueField.Equals(value) != true)) {
                    this.MaxTorqueField = value;
                    this.RaisePropertyChanged("MaxTorque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AbbTest2.ServiceReference1.Measure> Measures {
            get {
                return this.MeasuresField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasuresField, value) != true)) {
                    this.MeasuresField = value;
                    this.RaisePropertyChanged("Measures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MotorId {
            get {
                return this.MotorIdField;
            }
            set {
                if ((this.MotorIdField.Equals(value) != true)) {
                    this.MotorIdField = value;
                    this.RaisePropertyChanged("MotorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotorName {
            get {
                return this.MotorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorNameField, value) != true)) {
                    this.MotorNameField = value;
                    this.RaisePropertyChanged("MotorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<AbbTest2.ServiceReference1.MotorType> MotorType {
            get {
                return this.MotorTypeField;
            }
            set {
                if ((this.MotorTypeField.Equals(value) != true)) {
                    this.MotorTypeField = value;
                    this.RaisePropertyChanged("MotorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VoltageV {
            get {
                return this.VoltageVField;
            }
            set {
                if ((this.VoltageVField.Equals(value) != true)) {
                    this.VoltageVField = value;
                    this.RaisePropertyChanged("VoltageV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotorType", Namespace="http://schemas.datacontract.org/2004/07/AbbTest2.Models")]
    public enum MotorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Electric = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Combustion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hydraulic = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMeasures", ReplyAction="http://tempuri.org/IService/GetMeasuresResponse")]
        System.Collections.Generic.List<AbbTest2.ServiceReference1.Measure> GetMeasures();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : AbbTest2.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AbbTest2.ServiceReference1.IService>, AbbTest2.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AbbTest2.ServiceReference1.Measure> GetMeasures() {
            return base.Channel.GetMeasures();
        }
    }
}
